// Face Fit V1.0 规则数据（03A Face Fit 定稿版，2026-10-01）
// 与 TiDB 里 channel = face_fit 的 123 条规则、16 个原因码逐条一致（由同一份数据生成）。
// 只供离线测试使用，引擎运行时仍从数据库读取规则。改规则时两边要一起改。
// 数据库 matching_rules.reason_code 是 NOT NULL，neutral 规则统一填 FF_NEUTRAL 占位：
// 引擎对 neutral 命中不输出原因码（matching-core.ts），FF_NEUTRAL 也不写入 matching_reason_codes。
import { MatchingRule } from "../db/schema";

type Row = [string, string, string, string[], string, string[], string, string | null, string, string | null, string];

const ROWS: Row[] = [
  ["FF_001", "facial_line_echo", "cheek_contour", ["round"], "line_quality", ["curved","soft_curved"], "positive", "high", "4.0", "FF_CURVE_ECHO", "曲线五官 × 曲线服装"],
  ["FF_002", "facial_line_echo", "cheek_contour", ["round"], "line_quality", ["balanced"], "positive", "low", "4.0", "FF_CURVE_ECHO", "曲线五官 × 平衡线条"],
  ["FF_003", "facial_line_echo", "cheek_contour", ["round"], "line_quality", ["soft_straight"], "neutral", null, "4.0", "FF_NEUTRAL", "曲线五官 × 柔直线条"],
  ["FF_004", "facial_line_echo", "cheek_contour", ["round"], "line_quality", ["straight"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 直线服装"],
  ["FF_005", "facial_line_echo", "cheek_contour", ["round"], "line_quality", ["angular"], "penalty", "medium", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 锐角服装"],
  ["FF_006", "facial_line_echo", "cheek_contour", ["balanced"], "line_quality", ["balanced"], "positive", "high", "4.0", "FF_BALANCED_ECHO", "中性五官 × 平衡线条"],
  ["FF_007", "facial_line_echo", "cheek_contour", ["balanced"], "line_quality", ["soft_curved","soft_straight"], "positive", "medium", "4.0", "FF_BALANCED_ECHO", "中性五官 × 柔曲/柔直"],
  ["FF_008", "facial_line_echo", "cheek_contour", ["balanced"], "line_quality", ["curved","straight"], "neutral", null, "4.0", "FF_NEUTRAL", "中性五官 × 明显曲/直"],
  ["FF_009", "facial_line_echo", "cheek_contour", ["balanced"], "line_quality", ["angular"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "中性五官 × 锐角服装"],
  ["FF_010", "facial_line_echo", "cheek_contour", ["angular"], "line_quality", ["straight","angular"], "positive", "high", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 直线/锐角服装"],
  ["FF_011", "facial_line_echo", "cheek_contour", ["angular"], "line_quality", ["soft_straight"], "positive", "medium", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 柔直线条"],
  ["FF_012", "facial_line_echo", "cheek_contour", ["angular"], "line_quality", ["balanced"], "neutral", null, "4.0", "FF_NEUTRAL", "直线五官 × 平衡线条"],
  ["FF_013", "facial_line_echo", "cheek_contour", ["angular"], "line_quality", ["soft_curved"], "penalty", "low", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 柔曲服装"],
  ["FF_014", "facial_line_echo", "cheek_contour", ["angular"], "line_quality", ["curved"], "penalty", "medium", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 曲线服装"],
  ["FF_015", "facial_line_echo", "cheekbone_shape", ["rounded"], "line_quality", ["curved","soft_curved"], "positive", "high", "4.0", "FF_CURVE_ECHO", "曲线五官 × 曲线服装"],
  ["FF_016", "facial_line_echo", "cheekbone_shape", ["rounded"], "line_quality", ["balanced"], "positive", "low", "4.0", "FF_CURVE_ECHO", "曲线五官 × 平衡线条"],
  ["FF_017", "facial_line_echo", "cheekbone_shape", ["rounded"], "line_quality", ["soft_straight"], "neutral", null, "4.0", "FF_NEUTRAL", "曲线五官 × 柔直线条"],
  ["FF_018", "facial_line_echo", "cheekbone_shape", ["rounded"], "line_quality", ["straight"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 直线服装"],
  ["FF_019", "facial_line_echo", "cheekbone_shape", ["rounded"], "line_quality", ["angular"], "penalty", "medium", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 锐角服装"],
  ["FF_020", "facial_line_echo", "cheekbone_shape", ["balanced"], "line_quality", ["balanced"], "positive", "high", "4.0", "FF_BALANCED_ECHO", "中性五官 × 平衡线条"],
  ["FF_021", "facial_line_echo", "cheekbone_shape", ["balanced"], "line_quality", ["soft_curved","soft_straight"], "positive", "medium", "4.0", "FF_BALANCED_ECHO", "中性五官 × 柔曲/柔直"],
  ["FF_022", "facial_line_echo", "cheekbone_shape", ["balanced"], "line_quality", ["curved","straight"], "neutral", null, "4.0", "FF_NEUTRAL", "中性五官 × 明显曲/直"],
  ["FF_023", "facial_line_echo", "cheekbone_shape", ["balanced"], "line_quality", ["angular"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "中性五官 × 锐角服装"],
  ["FF_024", "facial_line_echo", "cheekbone_shape", ["angular"], "line_quality", ["straight","angular"], "positive", "high", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 直线/锐角服装"],
  ["FF_025", "facial_line_echo", "cheekbone_shape", ["angular"], "line_quality", ["soft_straight"], "positive", "medium", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 柔直线条"],
  ["FF_026", "facial_line_echo", "cheekbone_shape", ["angular"], "line_quality", ["balanced"], "neutral", null, "4.0", "FF_NEUTRAL", "直线五官 × 平衡线条"],
  ["FF_027", "facial_line_echo", "cheekbone_shape", ["angular"], "line_quality", ["soft_curved"], "penalty", "low", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 柔曲服装"],
  ["FF_028", "facial_line_echo", "cheekbone_shape", ["angular"], "line_quality", ["curved"], "penalty", "medium", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 曲线服装"],
  ["FF_029", "facial_line_echo", "chin_shape", ["round"], "line_quality", ["curved","soft_curved"], "positive", "high", "4.0", "FF_CURVE_ECHO", "曲线五官 × 曲线服装"],
  ["FF_030", "facial_line_echo", "chin_shape", ["round"], "line_quality", ["balanced"], "positive", "low", "4.0", "FF_CURVE_ECHO", "曲线五官 × 平衡线条"],
  ["FF_031", "facial_line_echo", "chin_shape", ["round"], "line_quality", ["soft_straight"], "neutral", null, "4.0", "FF_NEUTRAL", "曲线五官 × 柔直线条"],
  ["FF_032", "facial_line_echo", "chin_shape", ["round"], "line_quality", ["straight"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 直线服装"],
  ["FF_033", "facial_line_echo", "chin_shape", ["round"], "line_quality", ["angular"], "penalty", "medium", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 锐角服装"],
  ["FF_034", "facial_line_echo", "chin_shape", ["pointed","square"], "line_quality", ["straight","angular"], "positive", "high", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 直线/锐角服装"],
  ["FF_035", "facial_line_echo", "chin_shape", ["pointed","square"], "line_quality", ["soft_straight"], "positive", "medium", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 柔直线条"],
  ["FF_036", "facial_line_echo", "chin_shape", ["pointed","square"], "line_quality", ["balanced"], "neutral", null, "4.0", "FF_NEUTRAL", "直线五官 × 平衡线条"],
  ["FF_037", "facial_line_echo", "chin_shape", ["pointed","square"], "line_quality", ["soft_curved"], "penalty", "low", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 柔曲服装"],
  ["FF_038", "facial_line_echo", "chin_shape", ["pointed","square"], "line_quality", ["curved"], "penalty", "medium", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 曲线服装"],
  ["FF_039", "facial_line_echo", "nose_shape", ["round"], "line_quality", ["curved","soft_curved"], "positive", "high", "4.0", "FF_CURVE_ECHO", "曲线五官 × 曲线服装"],
  ["FF_040", "facial_line_echo", "nose_shape", ["round"], "line_quality", ["balanced"], "positive", "low", "4.0", "FF_CURVE_ECHO", "曲线五官 × 平衡线条"],
  ["FF_041", "facial_line_echo", "nose_shape", ["round"], "line_quality", ["soft_straight"], "neutral", null, "4.0", "FF_NEUTRAL", "曲线五官 × 柔直线条"],
  ["FF_042", "facial_line_echo", "nose_shape", ["round"], "line_quality", ["straight"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 直线服装"],
  ["FF_043", "facial_line_echo", "nose_shape", ["round"], "line_quality", ["angular"], "penalty", "medium", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 锐角服装"],
  ["FF_044", "facial_line_echo", "nose_shape", ["balanced"], "line_quality", ["balanced"], "positive", "high", "4.0", "FF_BALANCED_ECHO", "中性五官 × 平衡线条"],
  ["FF_045", "facial_line_echo", "nose_shape", ["balanced"], "line_quality", ["soft_curved","soft_straight"], "positive", "medium", "4.0", "FF_BALANCED_ECHO", "中性五官 × 柔曲/柔直"],
  ["FF_046", "facial_line_echo", "nose_shape", ["balanced"], "line_quality", ["curved","straight"], "neutral", null, "4.0", "FF_NEUTRAL", "中性五官 × 明显曲/直"],
  ["FF_047", "facial_line_echo", "nose_shape", ["balanced"], "line_quality", ["angular"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "中性五官 × 锐角服装"],
  ["FF_048", "facial_line_echo", "nose_shape", ["angular"], "line_quality", ["straight","angular"], "positive", "high", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 直线/锐角服装"],
  ["FF_049", "facial_line_echo", "nose_shape", ["angular"], "line_quality", ["soft_straight"], "positive", "medium", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 柔直线条"],
  ["FF_050", "facial_line_echo", "nose_shape", ["angular"], "line_quality", ["balanced"], "neutral", null, "4.0", "FF_NEUTRAL", "直线五官 × 平衡线条"],
  ["FF_051", "facial_line_echo", "nose_shape", ["angular"], "line_quality", ["soft_curved"], "penalty", "low", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 柔曲服装"],
  ["FF_052", "facial_line_echo", "nose_shape", ["angular"], "line_quality", ["curved"], "penalty", "medium", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 曲线服装"],
  ["FF_053", "facial_line_echo", "eye_shape", ["round"], "line_quality", ["curved","soft_curved"], "positive", "high", "4.0", "FF_CURVE_ECHO", "曲线五官 × 曲线服装"],
  ["FF_054", "facial_line_echo", "eye_shape", ["round"], "line_quality", ["balanced"], "positive", "low", "4.0", "FF_CURVE_ECHO", "曲线五官 × 平衡线条"],
  ["FF_055", "facial_line_echo", "eye_shape", ["round"], "line_quality", ["soft_straight"], "neutral", null, "4.0", "FF_NEUTRAL", "曲线五官 × 柔直线条"],
  ["FF_056", "facial_line_echo", "eye_shape", ["round"], "line_quality", ["straight"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 直线服装"],
  ["FF_057", "facial_line_echo", "eye_shape", ["round"], "line_quality", ["angular"], "penalty", "medium", "4.0", "FF_LINE_TOO_SHARP", "曲线五官 × 锐角服装"],
  ["FF_058", "facial_line_echo", "eye_shape", ["almond"], "line_quality", ["balanced"], "positive", "high", "4.0", "FF_BALANCED_ECHO", "中性五官 × 平衡线条"],
  ["FF_059", "facial_line_echo", "eye_shape", ["almond"], "line_quality", ["soft_curved","soft_straight"], "positive", "medium", "4.0", "FF_BALANCED_ECHO", "中性五官 × 柔曲/柔直"],
  ["FF_060", "facial_line_echo", "eye_shape", ["almond"], "line_quality", ["curved","straight"], "neutral", null, "4.0", "FF_NEUTRAL", "中性五官 × 明显曲/直"],
  ["FF_061", "facial_line_echo", "eye_shape", ["almond"], "line_quality", ["angular"], "penalty", "low", "4.0", "FF_LINE_TOO_SHARP", "中性五官 × 锐角服装"],
  ["FF_062", "facial_line_echo", "eye_shape", ["long"], "line_quality", ["straight","angular"], "positive", "high", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 直线/锐角服装"],
  ["FF_063", "facial_line_echo", "eye_shape", ["long"], "line_quality", ["soft_straight"], "positive", "medium", "4.0", "FF_STRAIGHT_ECHO", "直线五官 × 柔直线条"],
  ["FF_064", "facial_line_echo", "eye_shape", ["long"], "line_quality", ["balanced"], "neutral", null, "4.0", "FF_NEUTRAL", "直线五官 × 平衡线条"],
  ["FF_065", "facial_line_echo", "eye_shape", ["long"], "line_quality", ["soft_curved"], "penalty", "low", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 柔曲服装"],
  ["FF_066", "facial_line_echo", "eye_shape", ["long"], "line_quality", ["curved"], "penalty", "medium", "4.0", "FF_LINE_TOO_SOFT", "直线五官 × 曲线服装"],
  ["FF_067", "feature_scale_echo", "eye_size", ["small"], "visual_volume", ["very_small","small"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "小量感五官 × 小体量"],
  ["FF_068", "feature_scale_echo", "eye_size", ["small"], "visual_volume", ["medium"], "neutral", null, "2.5", "FF_NEUTRAL", "小量感五官 × 中体量"],
  ["FF_069", "feature_scale_echo", "eye_size", ["small"], "visual_volume", ["large"], "penalty", "low", "2.5", "FF_SCALE_OVERWHELM", "小量感五官 × 大体量"],
  ["FF_070", "feature_scale_echo", "eye_size", ["small"], "visual_volume", ["very_large"], "penalty", "medium", "2.5", "FF_SCALE_OVERWHELM", "小量感五官 × 超大体量"],
  ["FF_071", "feature_scale_echo", "eye_size", ["medium"], "visual_volume", ["medium"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "中量感五官 × 中体量"],
  ["FF_072", "feature_scale_echo", "eye_size", ["medium"], "visual_volume", ["small","large"], "positive", "low", "2.5", "FF_SCALE_ECHO", "中量感五官 × 相邻体量"],
  ["FF_073", "feature_scale_echo", "eye_size", ["medium"], "visual_volume", ["very_small","very_large"], "neutral", null, "2.5", "FF_NEUTRAL", "中量感五官 × 极端体量"],
  ["FF_074", "feature_scale_echo", "eye_size", ["large"], "visual_volume", ["large","very_large"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "大量感五官 × 大体量"],
  ["FF_075", "feature_scale_echo", "eye_size", ["large"], "visual_volume", ["medium"], "neutral", null, "2.5", "FF_NEUTRAL", "大量感五官 × 中体量"],
  ["FF_076", "feature_scale_echo", "eye_size", ["large"], "visual_volume", ["small"], "penalty", "low", "2.5", "FF_SCALE_UNDERWHELM", "大量感五官 × 小体量"],
  ["FF_077", "feature_scale_echo", "eye_size", ["large"], "visual_volume", ["very_small"], "penalty", "medium", "2.5", "FF_SCALE_UNDERWHELM", "大量感五官 × 超小体量"],
  ["FF_078", "feature_scale_echo", "nose_size", ["small"], "visual_volume", ["very_small","small"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "小量感五官 × 小体量"],
  ["FF_079", "feature_scale_echo", "nose_size", ["small"], "visual_volume", ["medium"], "neutral", null, "2.5", "FF_NEUTRAL", "小量感五官 × 中体量"],
  ["FF_080", "feature_scale_echo", "nose_size", ["small"], "visual_volume", ["large"], "penalty", "low", "2.5", "FF_SCALE_OVERWHELM", "小量感五官 × 大体量"],
  ["FF_081", "feature_scale_echo", "nose_size", ["small"], "visual_volume", ["very_large"], "penalty", "medium", "2.5", "FF_SCALE_OVERWHELM", "小量感五官 × 超大体量"],
  ["FF_082", "feature_scale_echo", "nose_size", ["medium"], "visual_volume", ["medium"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "中量感五官 × 中体量"],
  ["FF_083", "feature_scale_echo", "nose_size", ["medium"], "visual_volume", ["small","large"], "positive", "low", "2.5", "FF_SCALE_ECHO", "中量感五官 × 相邻体量"],
  ["FF_084", "feature_scale_echo", "nose_size", ["medium"], "visual_volume", ["very_small","very_large"], "neutral", null, "2.5", "FF_NEUTRAL", "中量感五官 × 极端体量"],
  ["FF_085", "feature_scale_echo", "nose_size", ["large"], "visual_volume", ["large","very_large"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "大量感五官 × 大体量"],
  ["FF_086", "feature_scale_echo", "nose_size", ["large"], "visual_volume", ["medium"], "neutral", null, "2.5", "FF_NEUTRAL", "大量感五官 × 中体量"],
  ["FF_087", "feature_scale_echo", "nose_size", ["large"], "visual_volume", ["small"], "penalty", "low", "2.5", "FF_SCALE_UNDERWHELM", "大量感五官 × 小体量"],
  ["FF_088", "feature_scale_echo", "nose_size", ["large"], "visual_volume", ["very_small"], "penalty", "medium", "2.5", "FF_SCALE_UNDERWHELM", "大量感五官 × 超小体量"],
  ["FF_089", "feature_scale_echo", "mouth_fullness", ["thin"], "visual_volume", ["very_small","small"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "小量感五官 × 小体量"],
  ["FF_090", "feature_scale_echo", "mouth_fullness", ["thin"], "visual_volume", ["medium"], "neutral", null, "2.5", "FF_NEUTRAL", "小量感五官 × 中体量"],
  ["FF_091", "feature_scale_echo", "mouth_fullness", ["thin"], "visual_volume", ["large"], "penalty", "low", "2.5", "FF_SCALE_OVERWHELM", "小量感五官 × 大体量"],
  ["FF_092", "feature_scale_echo", "mouth_fullness", ["thin"], "visual_volume", ["very_large"], "penalty", "medium", "2.5", "FF_SCALE_OVERWHELM", "小量感五官 × 超大体量"],
  ["FF_093", "feature_scale_echo", "mouth_fullness", ["medium"], "visual_volume", ["medium"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "中量感五官 × 中体量"],
  ["FF_094", "feature_scale_echo", "mouth_fullness", ["medium"], "visual_volume", ["small","large"], "positive", "low", "2.5", "FF_SCALE_ECHO", "中量感五官 × 相邻体量"],
  ["FF_095", "feature_scale_echo", "mouth_fullness", ["medium"], "visual_volume", ["very_small","very_large"], "neutral", null, "2.5", "FF_NEUTRAL", "中量感五官 × 极端体量"],
  ["FF_096", "feature_scale_echo", "mouth_fullness", ["full"], "visual_volume", ["large","very_large"], "positive", "medium", "2.5", "FF_SCALE_ECHO", "大量感五官 × 大体量"],
  ["FF_097", "feature_scale_echo", "mouth_fullness", ["full"], "visual_volume", ["medium"], "neutral", null, "2.5", "FF_NEUTRAL", "大量感五官 × 中体量"],
  ["FF_098", "feature_scale_echo", "mouth_fullness", ["full"], "visual_volume", ["small"], "penalty", "low", "2.5", "FF_SCALE_UNDERWHELM", "大量感五官 × 小体量"],
  ["FF_099", "feature_scale_echo", "mouth_fullness", ["full"], "visual_volume", ["very_small"], "penalty", "medium", "2.5", "FF_SCALE_UNDERWHELM", "大量感五官 × 超小体量"],
  ["FF_100", "contour_depth_echo", "cheekbone_prominence", ["low"], "structure_level", ["soft","soft_medium"], "positive", "medium", "1.5", "FF_DEPTH_ECHO", "立体度低 × 柔软"],
  ["FF_101", "contour_depth_echo", "cheekbone_prominence", ["low"], "structure_level", ["medium"], "neutral", null, "1.5", "FF_NEUTRAL", "立体度低 × 中等结构"],
  ["FF_102", "contour_depth_echo", "cheekbone_prominence", ["low"], "structure_level", ["medium_structured","structured"], "penalty", "low", "1.5", "FF_STRUCTURE_TOO_STRONG", "立体度低 × 强结构"],
  ["FF_103", "contour_depth_echo", "cheekbone_prominence", ["moderate"], "structure_level", ["soft_medium","medium","medium_structured"], "positive", "low", "1.5", "FF_DEPTH_ECHO", "立体度中 × 中段结构"],
  ["FF_104", "contour_depth_echo", "cheekbone_prominence", ["moderate"], "structure_level", ["soft","structured"], "neutral", null, "1.5", "FF_NEUTRAL", "立体度中 × 两端结构"],
  ["FF_105", "contour_depth_echo", "cheekbone_prominence", ["prominent"], "structure_level", ["medium_structured","structured"], "positive", "medium", "1.5", "FF_DEPTH_ECHO", "立体度高 × 强结构"],
  ["FF_106", "contour_depth_echo", "cheekbone_prominence", ["prominent"], "structure_level", ["medium"], "neutral", null, "1.5", "FF_NEUTRAL", "立体度高 × 中等结构"],
  ["FF_107", "contour_depth_echo", "cheekbone_prominence", ["prominent"], "structure_level", ["soft","soft_medium"], "penalty", "low", "1.5", "FF_STRUCTURE_TOO_WEAK", "立体度高 × 柔软"],
  ["FF_108", "contour_depth_echo", "nose_projection", ["flat"], "structure_level", ["soft","soft_medium"], "positive", "medium", "1.5", "FF_DEPTH_ECHO", "立体度低 × 柔软"],
  ["FF_109", "contour_depth_echo", "nose_projection", ["flat"], "structure_level", ["medium"], "neutral", null, "1.5", "FF_NEUTRAL", "立体度低 × 中等结构"],
  ["FF_110", "contour_depth_echo", "nose_projection", ["flat"], "structure_level", ["medium_structured","structured"], "penalty", "low", "1.5", "FF_STRUCTURE_TOO_STRONG", "立体度低 × 强结构"],
  ["FF_111", "contour_depth_echo", "nose_projection", ["medium"], "structure_level", ["soft_medium","medium","medium_structured"], "positive", "low", "1.5", "FF_DEPTH_ECHO", "立体度中 × 中段结构"],
  ["FF_112", "contour_depth_echo", "nose_projection", ["medium"], "structure_level", ["soft","structured"], "neutral", null, "1.5", "FF_NEUTRAL", "立体度中 × 两端结构"],
  ["FF_113", "contour_depth_echo", "nose_projection", ["prominent"], "structure_level", ["medium_structured","structured"], "positive", "medium", "1.5", "FF_DEPTH_ECHO", "立体度高 × 强结构"],
  ["FF_114", "contour_depth_echo", "nose_projection", ["prominent"], "structure_level", ["medium"], "neutral", null, "1.5", "FF_NEUTRAL", "立体度高 × 中等结构"],
  ["FF_115", "contour_depth_echo", "nose_projection", ["prominent"], "structure_level", ["soft","soft_medium"], "penalty", "low", "1.5", "FF_STRUCTURE_TOO_WEAK", "立体度高 × 柔软"],
  ["FF_116", "neckline_proportion", "chin_length", ["short"], "neckline", ["v_neck","deep_v"], "positive", "medium", "2.0", "FF_NECKLINE_ELONGATE", "下巴短 × V 领拉长"],
  ["FF_117", "neckline_proportion", "chin_length", ["short"], "neckline", ["turtleneck","mock_neck","stand_collar"], "penalty", "low", "2.0", "FF_NECKLINE_SHORTEN", "下巴短 × 高领压缩"],
  ["FF_118", "neckline_proportion", "chin_length", ["long"], "neckline", ["turtleneck","mock_neck","stand_collar","boat"], "positive", "low", "2.0", "FF_NECKLINE_BALANCE", "下巴长 × 高领/一字领平衡"],
  ["FF_119", "neckline_proportion", "chin_length", ["long"], "neckline", ["deep_v"], "penalty", "low", "2.0", "FF_NECKLINE_OVER_ELONGATE", "下巴长 × 深 V 进一步拉长"],
  ["FF_120", "neckline_proportion", "cheek_fullness", ["full"], "neckline", ["v_neck","deep_v"], "positive", "medium", "2.0", "FF_NECKLINE_ELONGATE", "面颊饱满 × V 领拉长"],
  ["FF_121", "neckline_proportion", "cheek_fullness", ["full"], "neckline", ["crew","round","boat"], "penalty", "low", "2.0", "FF_NECKLINE_WIDEN", "面颊饱满 × 圆领/一字领加宽"],
  ["FF_122", "neckline_proportion", "cheek_fullness", ["lean"], "neckline", ["turtleneck","mock_neck","boat","crew"], "positive", "low", "2.0", "FF_NECKLINE_BALANCE", "面颊清瘦 × 高领/一字领填充"],
  ["FF_123", "neckline_proportion", "cheek_fullness", ["lean"], "neckline", ["deep_v"], "penalty", "low", "2.0", "FF_NECKLINE_OVER_ELONGATE", "面颊清瘦 × 深 V 显瘦削"],
];

export const FACE_FIT_REASONS: [string, string, "strength" | "warning"][] = [
  ["FF_CURVE_ECHO", "服装的曲线线条与柔和的五官相呼应", "strength"],
  ["FF_BALANCED_ECHO", "服装线条平衡适中，与五官协调", "strength"],
  ["FF_STRAIGHT_ECHO", "服装的直线线条与利落的五官相呼应", "strength"],
  ["FF_LINE_TOO_SHARP", "服装线条偏硬朗，可能压过柔和的五官", "warning"],
  ["FF_LINE_TOO_SOFT", "服装线条偏圆润，可能削弱利落的五官", "warning"],
  ["FF_SCALE_ECHO", "服装体量与五官量感相称", "strength"],
  ["FF_SCALE_OVERWHELM", "服装体量偏大，可能盖过精致的五官", "warning"],
  ["FF_SCALE_UNDERWHELM", "服装体量偏小，撑不起较大的五官量感", "warning"],
  ["FF_DEPTH_ECHO", "服装结构感与面部立体度相称", "strength"],
  ["FF_STRUCTURE_TOO_STRONG", "服装结构感偏强，面部立体度不足以承接", "warning"],
  ["FF_STRUCTURE_TOO_WEAK", "服装偏软塌，与立体的面部轮廓不够呼应", "warning"],
  ["FF_NECKLINE_ELONGATE", "领口线条有拉长脸部比例的效果", "strength"],
  ["FF_NECKLINE_BALANCE", "领型能平衡偏长或偏瘦的脸部比例", "strength"],
  ["FF_NECKLINE_SHORTEN", "高领会让偏短的下巴显得更短", "warning"],
  ["FF_NECKLINE_WIDEN", "领口横向线条会让饱满的面颊显得更宽", "warning"],
  ["FF_NECKLINE_OVER_ELONGATE", "深 V 会让脸部显得更长或更瘦削", "warning"],
];

export function faceFitRules(): MatchingRule[] {
  return ROWS.map(([ruleId, subDimension, humanField, humanValue, itemField, itemValue, matchType, strength, ruleWeight, reasonCode, note], i) => ({
    id: 10000 + i, ruleId, channel: "face_fit", subDimension, humanField, humanValue, itemField, itemValue,
    matchType, strength, ruleWeight, isActive: true, constraintScope: null, scoreDelta: null,
    reasonCode, ruleVersion: "v1.0", note, createdAt: new Date(), updatedAt: new Date(),
  } as MatchingRule));
}
